version: "2.1"

volumes:
  dashboard-data:
  sense-data: {}

services:
  dashboard:
    image: bh.cr/balenalabs/dashboard
    restart: always
    volumes:
      - "dashboard-data:/data"
    ports:
      - "80"
