FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-python:3-run  

RUN install_packages \
      fontconfig

WORKDIR /usr/src/app

RUN apk add grafana --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community/ --allow-untrusted
RUN pip install stringcase

COPY ./provisioning /usr/share/grafana/conf/provisioning
COPY templates ./templates
COPY ./entry.sh .
COPY ./*.py ./

CMD ["/bin/sh","./entry.sh"]